theme: jekyll-theme-slate
title: [Arbitious利用マニュアル]
description: [仮想通貨自動裁定取引ツール]
#github: "false"
github:
  repository_url: 
  "is_project_page": "false"
#  repository_url: http://example.com
#show_downloads: "false"
#github:
#  is_project_page: false